export enum CloudInstanceState {
    UNKNOWN = 'UNKNOWN',
    BUILDING = 'BUILDING',
    STARTING = 'STARTING',
    ACTIVE = 'ACTIVE',
    STOPPING = 'STOPPING',
    STOPPED = 'STOPPED',
    REBOOTING = 'REBOOTING',
    UNAVAILABLE = 'UNAVAILABLE',
    ERROR = 'ERROR',
    DELETED = 'DELETED',
    PROVISIONING = 'PROVISIONING',
    STAGING = 'STAGING',
    RUNNING = 'RUNNING',
    SUSPENDING = 'SUSPENDING',
    SUSPENDED = 'SUSPENDED',
    TERMINATED = 'TERMINATED',
    REPAIRING = 'REPAIRING'
}
